# Inspired by https://github.com/uber/h3/blob/master/.travis.yml
# and https://github.com/google/s2geometry/blob/master/.travis.yml

language: c

os: linux
dist: bionic

addons:
  homebrew:
    packages:
    - apache-arrow

env:
  DEPS_ARCH: x64-linux

matrix:
  include:
    # Check that clang-format doesn't detect some files are not formatted.
    - name: "Formatting check"
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-format-9
      script: make format && git diff --exit-code
    # TODO: Doesn't install arrow correctly on OSX
    # - name: "Mac OSX (Xcode 11.3)"
    #   os: osx
    #   osx_image: xcode11.3
    #   env:
    #     DEPS_ARCH: x64-osx
    - name: "Linux (Clang)"
      os: linux
      compiler: clang
    - name: "Linux (GCC) with Valgrind"
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - valgrind
      script:
        - make -j
        - valgrind --error-exitcode=99 ./tests

install:
  - git clone git@github.com:UnfoldedInc/deck.gl-native-dependencies.git deps
  - export "VCPKG_ROOT=deps/$DEPS_ARCH/vcpkg"
  - SKIP_VCPKG=true ./scripts/bootstrap-linux.sh

before_script:
  # Build out of source
  - mkdir build
  - cd build
  - cmake -DWARNINGS_AS_ERRORS=ON -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake ..

script:
  - make -j 16
  - CTEST_OUTPUT_ON_FAILURE=1 make test
