# Inspired by https://github.com/uber/h3/blob/master/.travis.yml
# and https://github.com/google/s2geometry/blob/master/.travis.yml
# and https://github.com/amaiorano/vectrexy/blob/master/.travis.yml

language: c

os: linux
dist: xenial

compiler:
  - gcc
  - clang

env:
  global:
    - DEPS_DIR=${HOME}/deps

matrix:
  include:
      # Check that clang-format doesn't detect some files are not formatted.
    - name: "Formatting check"
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-format-5.0
      script: make format && git diff --exit-code
    - name: "Valgrind test"
      compiler: gcc
      addons:
        apt:
          packages:
            - valgrind
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DWRAP_VALGRIND=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake .
      script:
        - make
        - CTEST_OUTPUT_ON_FAILURE=1 make test
    - name: "Mac OSX (Xcode 8)"
      os: osx

install:
  # Install vcpkg and dependencies
  - export CC=${CC_COMPILER}
  - export CXX=${CXX_COMPILER}
  - mkdir -p ${DEPS_DIR}/vcpkg
  - pushd ${DEPS_DIR}/vcpkg
  - git init
  - git remote add origin https://github.com/Microsoft/vcpkg.git
  - git fetch origin master
  - git checkout -b master origin/master
  - ./bootstrap-vcpkg.sh
  - ./vcpkg install jsoncpp gtest
  - popd

cache:
  directories:
    - ${DEPS_DIR}/vcpkg/installed

before_script:
  # Build out of source
  - mkdir build
  - cd build
  - cmake -DWARNINGS_AS_ERRORS=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake ..

script:
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
