# Inspired by https://github.com/uber/h3/blob/master/.travis.yml
# and https://github.com/google/s2geometry/blob/master/.travis.yml

language: c

os: linux
dist: bionic

matrix:
  include:
    # Check that clang-format doesn't detect some files are not formatted.
    - name: "Formatting check"
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-format-9
      script: make format && git diff --exit-code
    - name: "macOS (Xcode 11.3)"
      os: osx
      osx_image: xcode11.3
    # TODO: Does not build on Linux currently due to dependency issues
    # - name: "Linux (Clang)"
    #   os: linux
    #   compiler: clang
    - name: "Linux (GCC 9) with Valgrind"
      os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - valgrind
            - libglu1-mesa-dev
            - g++-9
      before_script:
        - mkdir build
        - cd build
        - cmake -DWARNINGS_AS_ERRORS=OFF -DDECK_ENABLE_GRAPHICS=OFF -DDECK_ENABLE_FORMAT=OFF -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
      script:
        - make -j
        - valgrind --error-exitcode=99 ./deckgl-bundle-tests

before_script:
  # Build out of source
  - mkdir build
  - cd build
  - cmake -DWARNINGS_AS_ERRORS=ON -DDECK_ENABLE_GRAPHICS=OFF ..

script:
  - make -j 16
  - CTEST_OUTPUT_ON_FAILURE=1 make test
