# Inspired by https://github.com/uber/h3/blob/master/.travis.yml
# and https://github.com/google/s2geometry/blob/master/.travis.yml

# Many builds are disabled here to save time. They should be enabled
# later (and they should be working.)

language: c

os: linux
dist: bionic

compiler:
  - gcc
  # - clang

matrix:
  include:
      # Check that clang-format doesn't detect some files are not formatted.
    # - name: "Formatting check"
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - clang-format-5.0
    #   script: make format && git diff --exit-code
    # - name: "Valgrind test"
    #   compiler: gcc
    #   addons:
    #     apt:
    #       packages:
    #         - valgrind
    #   before_script:
    #     - cmake -DCMAKE_BUILD_TYPE=Debug -DWRAP_VALGRIND=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake .
    #   script:
    #     - make
    #     - CTEST_OUTPUT_ON_FAILURE=1 make test
    - name: "Mac OSX (Xcode 10)"
      os: osx
      osx_image: xcode10.1
      before_install:
        - brew install apache-arrow

before_install:
  # Install arrow
  - pushd $HOME
  - wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
  - sudo apt install -y -V ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
  - sudo apt update
  - sudo install libarrow-dev
  - popd

install:
  # Install vcpkg and dependencies
  - pushd $HOME
  - if [ -d "$HOME/vcpkg/.git" ] ; then echo vcpkg cached ; else rm -rf vcpkg ; git clone https://github.com/Microsoft/vcpkg ; fi
  - cd vcpkg
  - git checkout .
  - git pull
  - ./bootstrap-vcpkg.sh
  # Try to avoid building unneeded debug versions of dependencies
  - echo "set(VCPKG_BUILD_TYPE release)" >> triplets/x64-osx.cmake
  - echo "set(VCPKG_BUILD_TYPE release)" >> triplets/x64-linux.cmake
  # Install our dependencies:
  - ./vcpkg install jsoncpp gtest --recurse
  - rm -rf buildtrees
  - popd

cache:
  directories:
    - ${HOME}/vcpkg

before_script:
  # Build out of source
  - mkdir build
  - cd build
  - cmake -DWARNINGS_AS_ERRORS=ON -DCMAKE_TOOLCHAIN_FILE=${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake ..

script:
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
