# Inspired by https://github.com/uber/h3/blob/master/.travis.yml
# and https://github.com/google/s2geometry/blob/master/.travis.yml

# Many builds are disabled here to save time. They should be enabled
# later (and they should be working.)

language: c

os: linux
dist: bionic

addons:
  homebrew:
    packages:
    - apache-arrow
    - jsoncpp
    - gtest
    - range-v3
  apt:
    packages:
    - libjsoncpp-dev
    - googletest
    - librange-v3-dev

matrix:
  include:
    # Check that clang-format doesn't detect some files are not formatted.
    - name: "Formatting check"
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-9.0
          packages:
            - clang-format-9
      script: make format && git diff --exit-code
    - name: "Valgrind test"
      compiler: gcc
      addons:
        apt:
          packages:
            - valgrind
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DWRAP_VALGRIND=ON -DCMAKE_TOOLCHAIN_FILE=${DEPS_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake .
      script:
        - make
        - CTEST_OUTPUT_ON_FAILURE=1 make test
    - name: "Mac OSX (Xcode 11.3)"
      os: osx
      osx_image: xcode11.3
      before_install: []
    - name: "Linux (Clang)"
      os: linux
      compiler: clang
    - name: "Linux (GCC)"
      os: linux
      compiler: gcc

before_install:
  # Install arrow
  - pushd $HOME
  - wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
  - sudo apt install -y -V ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
  - sudo apt update
  - sudo apt install libarrow-dev
  - popd

before_script:
  # Build out of source
  - ./scripts/bootstrap.sh
  - mkdir build
  - cd build
  - cmake -DWARNINGS_AS_ERRORS=ON ..

script:
  - make -j
  - CTEST_OUTPUT_ON_FAILURE=1 make test
